---
- name: Demo playbook
  hosts: localhost
  tasks:
    - name: Clone app from git
      git:
        repo: 'https://github.com/vanduyms/trello'
        dest: '/home/vanduyms/Desktop/app'
        clone: yes
        update: yes
    - name: add .env file to backend
      copy:
        src: '/home/vanduyms/Desktop/app/.env'
        dest: '/home/vanduyms/Desktop/app/trello/backend'
        mode: '0644'
    - name: Read .env file and echo content
      command: "cat /home/vanduyms/Desktop/app/.env"
      register: env_file_content

    - name: Echo the content of the .env file
      debug:
        msg: "{{ env_file_content.stdout }}"