---
- name: Demo playbook
  hosts: localhost
  tasks:
    - name: Clone app from git
      git:
        repo: 'https://github.com/vanduyms/trello'
        dest: '/ansible/app'
        clone: yes
        update: yes
    - name: add .env file to backend
      copy:
        src: '/ansible/app/.env'
        dest: '/ansible/app/trello/backend'
        mode: '0644'
    - name: Build and start the backend
      shell: |
        cd /ansible/app/trello/backend
        npm install
        npm run build
        npm run dev
      args:
        chdir: /ansible/app/trello/backend
    - name: Build and start the frontend
      shell: |
        cd /ansible/app/trello/frontend
        npm install
        npm run build
        npm run dev
      args:
        chdir: /ansible/app/trello/frontend