---
- name: Demo playbook
  hosts: localhost
  tasks:
    - name: Clone app from git
      git:
        repo: 'https://github.com/vanduyms/trello'
        dest:: '~/home/Desktop/app'
        clone: yes
        update: yes
    - name: add .env file to backend
      copy:
        src: '~/.env'
        dest: '~/home/Desktop/app/trello/backend'
        mode: '0644'